### PR TITLE
Use execute() instead of executeUpdate() for afterLoad/beforeLoad

### PR DESCRIPTION
**Pull request by hiroyuki-sato**
Fixing #312 

I added test code to embulk-output-postgresql in #319.

@dmikurube and @hito4t 
Could you check when you get a chance?

Ref: https://embulk-dev.zulipchat.com/#narrow/stream/352993-embulk/topic/output-postgresql.20.3A.20support.20select.20in.20the.20after_load/near/345032157

### CODE REVIEW

**Review by dmikurube — COMMENTED** [review]
I'm not 100% confident about the difference between `execute` and `executeUpdate`, but it looks good from @hito4t's comment on Zulip.

One inline comment left about naming.

Also, how about naming this pull request's subject: `Use execute() instead of executeUpdate() for afterLoad/beforeLoad`

**Comment by hiroyuki-sato** [comment]
@dmikurube Thank you for your comment! I'll change the code.

**Comment by dmikurube** [comment]
@hiroyuki-sato Once you address the comment, I'll include it in the next v0.10.3.

**Comment by hiroyuki-sato** [comment]
@dmikurube Thanks. I'll fix as far as possible.

**Comment by dmikurube** [comment]
Okay, I tagged the `v0.10.3` milestone on this pull request.

**Comment by dmikurube** [comment]
I think I'll release v0.10.3 next Tuesday. I'll include it if it's ready by then.

**Comment by hiroyuki-sato** [comment]
@dmikurube Could you check when you have time?

**Review by dmikurube — APPROVED** [review]
Thanks!

The code looks good to me, and also @hito4t seems okay with this from his comment on Zulip.

> https://embulk-dev.zulipchat.com/#narrow/stream/352993-embulk/topic/output-postgresql.20.3A.20support.20select.20in.20the.20after_load/near/345032157

**Comment by naka-sho** [comment]
Thanks!

**Pull request merged**
