### PR TITLE
SSL support for Redshift output plugin

### PR DESCRIPTION
**Pull request by AntoineAugusti**

### CODE REVIEW

**Comment by AntoineAugusti** [comment]
I tried to use my fork locally (with `embulk run -L`) but did not succeed.

Can you explain how to build this plugin? Should I run commands at the root? Inside the redshift folder? Which commands?

It's complaining about a missing gemspec file

**Comment by hito4t** [comment]
Thank you for the PR!

`ssl` property accepts only specific values.
In such cases, we should use `enum` instead of `String` .
(Please see `insert_method` property of `OracleOutputPlugin` .)

embulk-input-postgresql, embulk-input-redshift and embulk-output-postgresql also have `ssl` properties, although they are boolean.
We should consider compatibility with them for avoiding confusion.

Namely, `ssl` property of embulk-output-redshift should be `true`, `false` or `verify` .
Or `enable`, `true` (same as `enable`), `disable`, `false` (same as `disable`), or `verify` .

Other plugins will also support `verify` in future.

And, `getSSL()` should be `getSsl()` as other plugins.


> Can you explain how to build this plugin? 

Please go to embulk-output-redshift directory and execute `../gradlew gem` .

**Comment by AntoineAugusti** [comment]
@hito4t Thanks for your detailed comment. I've introduced an enum as requested but it seems we cannot put `false` or `true` in enums, which makes sense to me.

**Comment by AntoineAugusti** [comment]
@hito4t Thanks for your detailed comment. Let me know if it looks better according to you

**Comment by hito4t** [comment]
Thank you!

I've tried to execute the codes.
Please check following comments.

- `Ssl#fromString` method needs the annotation `@JsonCreator`.

- Return type of `Ssl#fromString` should be `Ssl` instead of `Enum`.

- `Ssl#fromString` should throw `ConfigException` instead of `IllegalArgumentException` (see `AbstractJdbcOutputPlugin.Mode#fromString`).

- Error message of `Ssl#fromString` should contain `true` and `false`.

- Enum entries should be upper case (for example, `ENABLE`), and we should implement `toString` because config values are lower case (see `AbstractJdbcOutputPlugin.Mode#toString`).

- README for `ssl` should contain `true` and `false`.

**Comment by AntoineAugusti** [comment]
@hito4t Thanks for your detailed comment again. I've fixed what you asked. Sorry for not mentioning true and false, I felt that they were here only for compatibility reasons

**Comment by hito4t** [comment]
Thank you!

> Sorry for not mentioning true and false, I felt that they were here only for compatibility reasons

I think users will confuse if embulk-output-redshift README doesn't mention true and false because embulk-output-postgresql supports true and false.

I'll merge the PR.

**Comment by AntoineAugusti** [comment]
@hito4t Thanks a lot! Do you have a release date for 0.6.2?

**Comment by hito4t** [comment]
I'll release 0.6.2 in this week.

**Comment by hito4t** [comment]
I've released 0.6.2 !

**Pull request merged**
