### PR TITLE
Add modes, types, and options

### PR DESCRIPTION
**Pull request by frsyuki**
This pull-request includes:

* implementation of insert, insert_direct, merge, merge_direct, truncate_insert, and replace modes.
  * insert mode is renamed to insert_direct. insert is a new mode.
  * merge mode is renamed to merge_direct. merge is a new mode.
  * removed "merge_direct" mode support from postgresql. Instead, added new "merge" mode.
* implementation of java.sql.Types.TINYINT, SMALLINT, INTEGER, REAL, DATE, TIME, NUMERIC, DECIMAL, and NVARCHAR family.
  * BooleanColumnSetter doesn't parse string into boolean value any more.
  * TimestampColumnSetter doesn't allow string any more (#31)
  * instead, added string_pass_through option.
  * DATE type requires us to convert the timestamp to local time in Java code. So, I added `timezone` option.
  * `timezone` option is also used with `timestamp_format` option to convert a timestamp value into string column.
* if string_pass_through option is true, embulk lets the database parse the string into the column type. If the conversion fails, the task fails.
  * For example, MySQL and PostgreSQL support implicit type conversion from string to timestamp, and string to decimal.
* This code requires embulk >= 0.6.8 which will be released soon.
* Added AbstractJdbcOutputPlugin.Features class. This is used to configure maximum table name length, supported modes, and behavior of "merge" mode depending on the database implementation.

### CODE REVIEW

**Comment by hito4t** [comment]
It seems great improvement!
I have some comments.

About max table name length
* As discussed in #24 , some DBMSs measure a table name length by characters, not bytes.
* AbstractJdbcOutputPlugin#doBegin adds "%03d" to the result of generateIntermediateTableNamePrefix, so the table name will be over the max length.
* I think the default value of maxTableNameLegnth shouldn't be a specific value (256), because it may be too long for some DBMSs.
The subclasses of AbstractJdbcOutputPlugin should define, or users of JdbcOutputPlugin should set if needed.
* In OracleOutputPlugin#getFeatures, the constant MAX_TABLE_NAME_LENGTH should be used.

About timestamp format
* A table may have multiple date or timestamp columns, so we cannot define one timestamp format for the table.
I think users should use timestamp type and define formats per columns, or use string_pass_through and make DBMS convert.

About string pass through
* DBMSs can convert not only string values, but also other values (ex. convert int value into char(4)).
We may need to use pass through for other types for some reasons (ex. converting on DBMS may be faster than on Java).
We can apply pass through to all types (
https://gist.github.com/hito4t/d4dbaec63cc524773cad ).


Thanks.

**Comment by frsyuki** [comment]
> "%03d" 

Good catch. I fixed at abf1581cbe78b728c16c3bb1f6a8f1687b04a008.

> maxTableNameLegnth

Do you mean 256 is too long as the default value? Maybe true. I changed it to 30.
JdbcOutputPlugin has `max_table_name_length` option so that users can overwrite it.

> MAX_TABLE_NAME_LENGTH

Good point. I deleted MAX_TABLE_NAME_LENGTH constant because it's not used.

> timestamp format

Oh, is it likely that a table has multiple `varchar` (or clob, etc.) columns that stores timestamp? I assumed that users don't have to use `timestamp_format` option in most of cases because timestamp values will be stored using `date`, `time` or `timestamp` (or `timestamp with zone`) types.
Remember that timestamp_format is used for conversion from embulk's timestamp type to DB's text type.

> string pass through

Hm...do you think conversion int value to char(4) becomes really faster?
Do you have other use cases when pass-through is useful?

**Comment by hito4t** [comment]
> > timestamp format

> Remember that timestamp_format is used for conversion from embulk's timestamp type to DB's text type.

I'm sorry,  I misunderstood.


> > string pass through

> Hm...do you think conversion int value to char(4) becomes really faster?

Well, I think `batch.setDouble(d)` is faster than `batch.setBigDecimal(BigDecimal.valueOf(d))` .

> Do you have other use cases when pass-through is useful?

Embulk doesn't support all SQL types, but we may need to use a such type and the input type may not string.
For example:
* Copy records from MySQL to a some DBMS
* Use embulk-input-mysql and embulk-output-jdbc
* Input type is TIMESTAMP
* Output type is a kind of TIMESTAMP, but JDBC driver returns Types.OTHER
(Actually, Oracle 11 JDBC Driver returns Types.OTHER for TIMESTAMP(0))
* If timestamp values can be passed through, we can copy the values to the DBMS

**Comment by frsyuki** [comment]
> batch.setDouble(d) is faster than batch.setBigDecimal(BigDecimal.valueOf(d))

I see. That's an optimization by omitting strict type conversions semantics and error handling.

> Output type is a kind of TIMESTAMP, but JDBC driver returns Types.OTHER (Actually, Oracle 11 JDBC Driver returns Types.OTHER for TIMESTAMP(0))

aah....ok, I see. It means that `ColumnSetterFactory#newColumnSetter` throws an exception, right? It's a bug of JDBC driver and we need a workaround for that.
How about following ideas?:

* embulk-output-oracle (and probably embulk-output-postgresql) uses an optimized ColumnSetter if input is boolean/long/double and output is Types.DECIMAL or Types.NUMERIC. This optimized ColumnSetter uses `setByte`, `setLong`, or `setDouble` rather than `setBigInteger`. It assumes that Oracle/JDBC converts byte/long/double to NUMERIC(X) type using the same behavior with Java's `BigDecimal.valueOf(v)`. If this assumption is correct, this is a valid optimization. Its behavior isn't changed at all including error handling. There're no downside.
* pass-through is not free optimization because error handling is different (conversion failure in Java will set NULL but failure in DB causes error). So, it should be a customizable parameter.
* add `column_options` option to give full control of ColumnSetters to users. We write configuration file as following:

```yaml
out:
  type: oracle
  host: ...
  column_options:
    my_decimal_column1: {value_type: pass}  # always use PassThroughColumnSetter
    my_decimal_column2: {value_type: string}  # always use StringColumnSetter
    my_timestamp_column1: {value_type: timestamp}  # always use TimestampColumnSetter
    my_timestamp_column2: {value_type: string, timestamp_format: '%Y-%m-%d', timezone: 'UTC'}  # always use StringColumnSetter. If the value is timestamp, use the timestmap_format to convert it to string.
    my_timestamp_column4: {value_type: nstring}  # always use NStringColumnSetter
  # delete timestamp_format option. always use "%Y-%m-%d %H:%M:%S.%6N" as the default timestamp_format. Most of users don't need this option.
  # delete timezone option
  default_timezone: 'UTC'  # new option
```

`column_options` chooses ColumnSetter regardless of java.sql.Types. We can use either of byte, short, int, long, double, float, boolean, string, nstring, date, time, timestamp, decimal, or pass. "pass" is special which uses PassThroughColumnSetter.

**Comment by hito4t** [comment]
Thank for the great idea!

I've found some trivial bugs.

https://github.com/embulk/embulk-output-jdbc/blob/types/embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/setter/ColumnSetterFactory.java#L49
`"data"` should be `"date"`.

https://github.com/embulk/embulk-output-jdbc/blob/types/embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/JdbcColumn.java#L27
`"isNotNull"` should be `"notNull"`, otherwise `com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException` will be thrown.

**Comment by frsyuki** [comment]
Thank you for your comment.
We can go this way.

**Pull request merged**
