### PR TITLE
Add getDataLength for numeric without precision

### PR DESCRIPTION
**Pull request by shin1103**
This pull request is fixes issue #350

### CODE REVIEW

**Comment by dmikurube** [comment]
Thanks for your contribution!

The change seems good and reasonable, but do you have any reference in the PostgreSQL JDBC Driver that explains the difference? (For example, a pull request, an issue, or a commit in https://github.com/pgjdbc/pgjdbc)

**Comment by shin1103** [comment]
Thanks for early response.

I wrote why this difference is occurred in issue.  
https://github.com/embulk/embulk-output-jdbc/issues/350#issuecomment-2418149893

**Comment by dmikurube** [comment]
Sorry for being late.

Thanks for the pointers. Then, can you include those links and some more background information as a comment there in the code?  It'd help us in the future to track the context back.

Then I'll approve this. Also, can I hear your thoughts, @hiroyuki-sato @hito4t ?

**Comment by shin1103** [comment]
Thank you for the response.  
Add some comment about getDataLength. Please confirm.

**Review by hiroyuki-sato — APPROVED** [review]
LGTM👍 @shin1103 Thank you for creating this PR

**Review by dmikurube — APPROVED** [review]
Sorry for being late again, and thanks for working on it! LGTM2.

Let me wait for @hito4t for more 1-2 days, but will merge soon.

**Comment by dmikurube** [comment]
No response since 3 days ago. Let's merge this. Thanks for your contribution!

We'll be releasing v0.10.7 with this, but it may take some more time. Please let us know if you're in a hurry.

**Pull request merged**
