### PR TITLE
Update embulk 0 9

### PR DESCRIPTION
**Pull request by hiroyuki-sato**
Hello, @hito4t 
This PR implement #266.

Could you take a look when you get a chance?
I'll use [gradle-embulk-plugin](https://github.com/embulk/gradle-embulk-plugins) in a future.

I want to update PostgreSQL and MySQL JDBC Driver after merge this PR.

### CODE REVIEW

**Comment by hito4t** [comment]
@hiroyuki-sato 
Thank you!
I'll review as soon as possible.

**Comment by hiroyuki-sato** [comment]
Hello, @hito4t 
Thank you for your comment.

The core team (@dmikurube ) told me that v0.10 will change much around a `driver_path`.
[twitter](https://twitter.com/dmikurube/status/1234848021365559296?s=20) Japanese
So, I'll wait v0.10 development.

I already try MySQL connector/J 8 and MariaDB Connector/J. It need some modification, but It may work.
https://github.com/hiroyuki-sato/embulk-output-jdbc/commits/topic/update-mysql-jdbc

If we need to update PostgreSQL and MySQL JDBC driver sooner, I'll create another PR that just updates the driver version.
(But some options deprecated in Connector/J 8. ex. `useLegacyDatetimeCode` for example)

**Comment by hito4t** [comment]
Some tests failed in my environment.
Now I'm examining.

**Comment by hito4t** [comment]
> 
> 
> Some tests failed in my environment.
> Now I'm examining.

Some tests failed because of the following issue.
https://github.com/embulk/embulk/issues/1233

I'm trying to find a workaround.

**Comment by hito4t** [comment]
> Some tests failed because of the following issue.
> [embulk/embulk#1233](https://github.com/embulk/embulk/issues/1233)
> 
> I'm trying to find a workaround.

`Path#toRealPath` will resolve the problem.

**Comment by hito4t** [comment]
The test of embulk-output-db2 has timestamp data with picoseconds (`2016-09-11 12:34:45.123456789012`).
When the timestamp parser of embulk 0.8 parses it, it will be parsed down to microseconds and nanoseconds are truncated (namely, parsed as `2016-09-11 12:34:45.123456`).
But when the timestamp parser of embulk 0.9 parses it, the value under seconds will be truncated (namely, parsed as `2016-09-11 12:34:45.000000`).

That difference causes failures of some tests.

This problem will be resolved by cutting values under microseconds in the test data (namely, `2016-09-11 12:34:45.123456`).

**Comment by hiroyuki-sato** [comment]
@hito4t Thank you for testing this PR. 

As far as I know, this timestamp parser behavior isn't a known issue.
Shall we investigate this timestamp parser problem at first, 
After that, Will we consider how to change the code

At first, I created simple reproduce codes. It may OK, but I need print under milliseconds value.
https://github.com/hiroyuki-sato/embulk-support/tree/master/20200327_output-jdbc-timestamp

**Comment by hiroyuki-sato** [comment]
@hito4t  Created the Issue. https://github.com/embulk/embulk/issues/1235

**Comment by hito4t** [comment]
@hiroyuki-sato 
Thank you!
I found that nanoseconds are correctly parsed by both older parser and newer parser.
I've cut picoseconds in test data because they were not actually used in test.

**Comment by hiroyuki-sato** [comment]
Thank you!

**Pull request merged**
