### PR TITLE
Add {before|after}_load tests in the postgresql plugin

### PR DESCRIPTION
**Pull request by hiroyuki-sato**
Please review #317 before this PR.
This PR adds `before_load` and `after_load` tests in `embulk-output-postgresql` for preparing #313.

~~Commit 63a10abfaeb0aa273a7b06e5b83a0a18db26edf9 is the PR for this change.~~
~~Rest of commits are #317.~~

### CODE REVIEW

**Comment by hiroyuki-sato** [comment]
@dmikurube , @hito4t Could you take a look this PR when you get a chance?

**Review by dmikurube — APPROVED** [review]
LGTM. Adding tests is always nice! :)

**Comment by hiroyuki-sato** [comment]
@dmikurube Could you merge this PR? (I don't have permission)

**Comment by dmikurube** [comment]
Ah, sorry I forgot it. Thanks! Merging.

**Comment by hiroyuki-sato** [comment]
Thanks!

**Pull request merged**
