### PR TITLE
Check with GitHub Actions v3

### PR DESCRIPTION
**Pull request by hiroyuki-sato**
* Use `actions/checkout@v3`, `actions/setup-java@v3` and `actions/upload-artifact@v3`
* Use temurin JDK (It's the same JDK as the Embulk repository.)
* Run on push and pull_request (from a forked repository only)
* Add gradle cache.
* Add `fail-fast` strategy.

@dmikurube Could you take a look when you get a chance?
Especially, `gradle` and `strategy` part.

### CODE REVIEW

**Comment by dmikurube** [comment]
Let's rename `build.yml` to `check.yml`, and change `name: Build and test` to `name: Check`, to follow other repos consistently. Others look good.

**Comment by hiroyuki-sato** [comment]
Thank you for your review.

* Renamed `build.yml` to `check.yml`
* change `name: Build and test` to `name: Check`.
* Force pushed

```diff
diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
index be1ad5e..c67fd2d 100644
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -1,4 +1,4 @@
-name: Build and test
+name: Check
 on: push
 jobs:
   mysql:
```

**Review by dmikurube — APPROVED** [review]
Thanks. LGTM!

**Comment by hiroyuki-sato** [comment]
Thanks!

**Pull request merged**
