### PR TITLE
Update JDBC driver version to support utf8mb4

### PR DESCRIPTION
**Pull request by y-ken**
utf8mb4 supports emoji strings.
This patch fixes following issue.
https://github.com/embulk/embulk-input-jdbc/issues/114

I have proposed pull request like embulk-input-mysql
https://github.com/embulk/embulk-input-jdbc/pull/125

### CODE REVIEW

**Comment by hito4t** [comment]
Thank you for the PR!

I think before updating bundled MySQL JDBC driver, we should add feature to change JDBC driver as embulk-input-mysql did, because someone need to use old driver for compatibility.
https://github.com/embulk/embulk-input-jdbc/pull/116

By the way, is there any reason not to use latest driver (5.1.44) ?
https://dev.mysql.com/doc/relnotes/connector-j/5.1/en/news-5-1.html

**Comment by y-ken** [comment]
I have used mysql for over 15 years but I don't know the case of keep old version of java driver.
and, It is sure that is better to use latest driver version of 5.1.44.

**Comment by hito4t** [comment]
@y-ken 
Thank you!
I've create the PR ( #219 ) which enables embulk-output-mysql/postgresql to change JDBC driver.
I'll merge your PR after merging the PR.

**Comment by y-ken** [comment]
Thank you!
After merging #219, I'll update README version, too.
https://github.com/embulk/embulk-output-jdbc/pull/219/files#diff-68883e04f847f6f7934d2355ac02af59R13

**Comment by hito4t** [comment]
@y-ken 
Thank you!

**Pull request merged**
