### PR TITLE
Execute SQL before loading 

### PR DESCRIPTION
**Pull request by hito4t**

### CODE REVIEW

**Comment by hito4t** [comment]
This PR will resolve #161, #89 .

**Comment by hiroyuki-sato** [comment]
@hito4t 

I tried `before_test` branch.
Sorry for the delay. 

It seems that `before_load` sql execute **after** `DELETE` statement.
Is this correct?

The original user may want to execute `before_load` **before** DELETE statement. 

```yaml
out:
  type: postgresql
  mode: truncate_insert
  before_load: truncate table before_test
  table: before_test
  host: xxx.xxx.xxx.xxx
  user: user
  database: embulk_test
```

```
2017-04-04 17:46:43.561 +0900 [INFO] (0001:transaction): SQL: SET search_path TO "public"
2017-04-04 17:46:43.562 +0900 [INFO] (0001:transaction): > 0.00 seconds
2017-04-04 17:46:43.563 +0900 [INFO] (0001:transaction): SQL: DELETE FROM "before_test"
2017-04-04 17:46:43.564 +0900 [INFO] (0001:transaction): > 0.00 seconds (4 rows)
2017-04-04 17:46:43.565 +0900 [INFO] (0001:transaction): SQL: truncate table before_test
2017-04-04 17:46:43.572 +0900 [INFO] (0001:transaction): > 0.01 seconds
```

**Comment by hito4t** [comment]
@hiroyuki-sato 

> The original user may want to execute before_load before DELETE statement.

He may want to execute `TRUNCATE` statement instead of `DELETE` statement before `insert`.
He shouldn't use `truncate_insert` mode because it executes `DELETE` statement, but should use `insert` mode.
(Is is useless to execute both `TRUNCATE` and `DELETE`.)

The reason for executing `before_load` after `DELETE` statement is that it may insert records into the target table.

**Comment by hiroyuki-sato** [comment]
@hito4t
Oh, I see.
Can I use `before_load` in all modes?

**Comment by hito4t** [comment]
@hiroyuki-sato 
All modes except `replace` mode support `before_load`.
I think it is useless to execute SQL before `replace` because it will drop the target table.

**Comment by hiroyuki-sato** [comment]
The `before_load` in insert mode worked correctly. 

He can use `before_load` in `insert` mode instead of `truncate_insert`.

```yaml
out:
  type: postgresql
  mode: insert
  before_load: truncate table before_test
  table: before_test
  host: xxx.xxx.xxx.xxx
  user: user
  database: embulk_test
```

```
2017-04-05 16:52:25.302 +0900 [INFO] (0001:transaction): Using insert mode
...
2017-04-05 16:52:25.740 +0900 [INFO] (0001:transaction): SQL: truncate table before_test
```

**Comment by hito4t** [comment]
@hiroyuki-sato 
Thank you!

**Pull request merged**
