### PR TITLE
Add assume role authentication for Redshift

### PR DESCRIPTION
**Pull request by t3t5u**
Add assume role authentication for Redshift.
For this purpose, fetch the following PR.
https://github.com/embulk/embulk-util-aws-credentials/pull/8

### CODE REVIEW

**Review by hiroyuki-sato — APPROVED** [review]
LGTM👍

@dmikurube Please take a look when you have a time.

Just memo.
embulk-util-aws-credentials supprts assume_role from 0.4.1
https://github.com/embulk/embulk-util-aws-credentials/pull/8

**Review by dmikurube — APPROVED** [review]
LGTM, too. @hito4t Do you have any thoughts?

**Review by hito4t — APPROVED** [review]
LGTM!

**Comment by dmikurube** [comment]
Okay, let's merge this and release v0.10.4! Thanks for your contribution.

**Pull request merged**
