### PR TITLE
Catch up with Embulk v0.10 API/SPI in embulk-output-jdbc:0.10.0

### PR DESCRIPTION
**Pull request by dmikurube**
The next version will be a big change again, then bumping up to v0.10.0, not v0.9.1.

v0.10.0 plans to :
* Catch up with the Embulk v0.10 API/SPI https://dev.embulk.org/topics/get-ready-for-v0.11-and-v1.0.html
* Release JARs to Maven Central, not Bintray

For the Embulk v0.10 API/SPI catchup, please see https://dev.embulk.org/topics/get-ready-for-v0.11-and-v1.0.html and https://github.com/embulk/embulk-input-jdbc/pull/207, too.

### CODE REVIEW

**Review by vietnguyen-td — APPROVED** [review]
LGTM

**Review by hito4t — CHANGES_REQUESTED** [review]
@dmikurube 
The original `DoubleMath.roundToLong` will throw `ArithmeticException` if a value is less than `Long.MIN_VALUE` or greater than `Long.MAX_VALUE` .
https://guava.dev/releases/19.0/api/docs/com/google/common/math/DoubleMath.html#roundToLong(double,%20java.math.RoundingMode)
But the new `roundDoubleToLong` won't throw.

**Comment by dmikurube** [comment]
@hito4t Thanks for your comment! Good catch. We needed an equivalent to :
https://github.com/google/guava/blob/v18.0/guava/src/com/google/common/math/DoubleMath.java#L157

Addressed in 36c8950418dfbfdf4f4e634ae5b97e89b744547c. Could you have another look?

**Review by hito4t — APPROVED** [review]
LGTM!

**Comment by dmikurube** [comment]
Thanks!

**Pull request merged**
