### PR TITLE
Add merge_rule option to plugins that support merge

### LINKED ISSUE #110: Suggestion: Option to control how merge_direct updates existing rows
When using `merge_direct` on MySQL, there are cases that some columns must not be updated, or must be updated conditionally.
I implemented an option to manually specify `ON DUPLICATE KEY UPDATE` clause [patch](https://github.com/tomykaira/embulk-output-jdbc/commit/9e92858a7a9bf7ce32dcd9af1765fbed5c1da5bc). This option gives full control of how to update.

The drawback is that this option cannot cover other RDBMSs like PostgreSQL.
I appreciate if my change is merged, but I am afraid that such a method is not suitable for this project.
Let me know the opinion of maintainers. Thanks!

### PR DESCRIPTION
**Pull request by tomykaira**
merge_rule defines column values of existing rows.
This fixes #110.

Example

Table:

```sql
DROP TABLE if exists myscore;
CREATE TABLE myscore (
  id integer primary key,
  total_value integer default 0,
  updated_at integer
);
```

config:

```yml
# mysql
out:
  type: mysql
  table: myscore
  mode: merge_direct
  merge_rule:
    - total_value = total_value + VALUES(total_value)
    - updated_at = GREATEST(updated_at, VALUES(updated_at))

# postgresql
out:
  type: postgresql
  table: myscore
  mode: merge
  merge_rule:
    - total_value = myscore.total_value + S.total_value
    - updated_at = GREATEST(myscore.updated_at, S.updated_at)
```

@hito4t I am sorry for getting late. Would you review this?

### CODE REVIEW

**Comment by toyama0919** [comment]
awesome 😊

**Comment by frsyuki** [comment]
this idea looks good.
one comment is that it should throw config exception if it's not supported (oracle, redshift)

**Comment by tomykaira** [comment]
Good advice. I have added the functionality using `Features` and setting the flag in MySQL and Postgres.

**Comment by hito4t** [comment]
Thank you for the PR!
It must be very useful.

I have some comments as follows.
Would you check them?

- Many methods take both `mergeKeys` and `mergeRule` as parameters. By creating a class holding both values, the program should become more maintainable. 
- The example `foo = foo + VALUES(foo)` for embulk-output-mysql will not work in merge mode because `foo` is ambiguous, although It will work in merge_direct mode.

**Comment by tomykaira** [comment]
@hito4t 
Thank you for the advice.

> Many methods take both mergeKeys and mergeRule as parameters.

Yes, but `mergeKeys`'s type changes in the call tree. First the type is `Optional<List<String>>`, and `Optional` is removed until the leaf function. Should I create something like `MergeConfigOptional` and `MergeConfigFulfilled`?

> mysql plugin example

Sorry. I did not take it into consideration.I will present different example statement of the same meaning in README.

**Comment by hito4t** [comment]
>>    Many methods take both mergeKeys and mergeRule as parameters.
>
> Yes, but mergeKeys's type changes in the call tree. First the type is Optional<List<String>>, and Optional is removed until the leaf function. Should I create something like MergeConfigOptional and MergeConfigFulfilled?

My idea is as follows:

In yml, both `mergeKeys` and `mergeRule` are optional.
In `AbstractJdbcOutputPlugin#doBegin` , `mergeKeys` will be always set if mode is `merge` or `merge_direct`, and neither `mergeKeys` nor `mergeRule` is used in other modes.

Namely, `merge` and `merge_direct` mode use `List<String> mergeKeys` and `Optional<List<String>> mergeRule`, and other modes don't use both of them.

Therefore `MergeConfig` class should hold `List<String> mergeKeys` and `Optional<List<String>> mergeRule`.
Methods used in all modes (ex. `AbstractJdbcOutputPlugin#newBatchInsert`) should take `Optional<MergeConfig>` as a parameter.
And methods used only in `merge` or `merge_direct` mode (ex. `JdbcOutputConnection#collectMerge`) should take `MergeConfig` as a parameter.

**Comment by tomykaira** [comment]
@hito4t Thank you for detailed advice. I rewrote all arguments according to your idea. Could you check me again?

**Comment by hito4t** [comment]
Thank you!

https://github.com/embulk/embulk-output-jdbc/pull/115/files#diff-9a35ee43fc85ff7cdf95d5751eb49c3dR851
In `open` method `mergeKeys` will be always present if mode is `merge_direct`.

Because it will have been set in `doBegin` method.
https://github.com/tomykaira/embulk-output-jdbc/blob/cd096f132cad5f359b018d93377392478d529666/embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/AbstractJdbcOutputPlugin.java#L547
https://github.com/tomykaira/embulk-output-jdbc/blob/cd096f132cad5f359b018d93377392478d529666/embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/AbstractJdbcOutputPlugin.java#L564

**Comment by tomykaira** [comment]
@hito4t Thank you. I see. I have fixed the point at a9cd313.

**Comment by hito4t** [comment]
Thank you!
I'll merge in a few days.

**Pull request merged**
