### PR TITLE
allow access_key_id and secrett_access_key is null.

### PR DESCRIPTION
**Pull request by toyama0919**
Hello.

We use embulk-output-redshift.
I want use IAM instance profile.
This PR use DefaultAWSCredentialsProviderChain.
## DefaultAWSCredentialsProviderChain support

``` java
    public DefaultAWSCredentialsProviderChain() {
        super(new EnvironmentVariableCredentialsProvider(),
              new SystemPropertiesCredentialsProvider(),
              new ProfileCredentialsProvider(),
              new InstanceProfileCredentialsProvider());
    }
```

### CODE REVIEW

**Comment by frsyuki** [comment]
we should take the consistent way with embulk-input-s3:
https://github.com/embulk/embulk-input-s3/blob/master/embulk-input-s3/src/main/java/org/embulk/input/s3/AwsCredentials.java#L25

**Comment by toyama0919** [comment]
@frsyuki 
Thanks for your advice.
I fixed in the same way as embulk-input-s3.

**Comment by hito4t** [comment]
It looks very useful!

Would you check the following comments?

- If AWS credentials properties are not properly set, some records will be written in local temporary file, embulk-output-redshift will try to upload it to S3, and a ConfigException will be thrown. If ConfigException is thrown soon after running, it will be more user-friendly.

- embulk-input-s3 uses only S3, but embulk-output-redshift uses S3 and Redshift. I think some property names are a bit confusing. It is easier to understand if we add prefix such as "aws_" to them. For example, "aws_auth_method", "aws_session_token", "aws_profile_file" and "aws_profile_name". ("aws_access_key_id" may also be easier to understand, but we shouldn't change it for compatibility.)

**Comment by toyama0919** [comment]
@hito4t @frsyuki 
Sorry late response!


>If AWS credentials properties are not properly set, some records will be written in local temporary file, embulk-output-redshift will try to upload it to S3, and a ConfigException will be thrown. If ConfigException is thrown soon after running, it will be more user-friendly.

Is this `env properties` ?


>embulk-input-s3 uses only S3, but embulk-output-redshift uses S3 and Redshift. I think some property names are a bit confusing. It is easier to understand if we add prefix such as "aws_" to them. For example, "aws_auth_method", "aws_session_token", "aws_profile_file" and "aws_profile_name". ("aws_access_key_id" may also be easier to understand, but we shouldn't change it for compatibility.)

That’s right.
I will fix it.


There is one proposal.
I want make org.embulk.plugins.utils.AwsCredential and org.embulk.plugins.utils.AwsPluginTask to bintray.
What do you think?

**Comment by hito4t** [comment]
>> If AWS credentials properties are not properly set, some records will be written in local temporary file, embulk-output-redshift will try to upload it to S3, and a ConfigException will be thrown. If ConfigException is thrown soon after running, it will be more user-friendly.
>> 

> Is this env properties ?

I'm sorry.
Not a ConfigException,  but a AmazonS3Exception will be thrown.
We can check properties for AWS credentials by accessing AWS actually.
For example, we can try to access S3 in `RedshiftCopyBatchInsert` constructor, which is called before executing transactions.

> I want make org.embulk.plugins.utils.AwsCredential and org.embulk.plugins.utils.AwsPluginTask to bintray.

I think that's a nice idea because it's better to reuse source codes than to copy source codes.
But embulk-output-redshift and embulk-input-s3 may not be able to use same source codes if embulk-output-redshift append prefix "aws_" to property names.

@frsyuki what do you think about it?

**Comment by frsyuki** [comment]
code for AWS credentials should be shared.
I created this package: https://github.com/embulk/embulk-input-s3/pull/36

**Comment by hito4t** [comment]
> code for AWS credentials should be shared.
> I created this package: embulk/embulk-input-s3#36
> embulk-output-redshift should be able to use AwsCredentialsTaskWithPrefix.

Thank you!
We are waiting for embulk-util-aws-credentials to be uploaded to bintray.

**Comment by toyama0919** [comment]
@frsyuki

Oh thanks!
I will integrate by AwsCredentialsTaskWithPrefix.

**Comment by toyama0919** [comment]
@frsyuki 
waiting upload embulk-util-aws-credentials..

**Comment by muga** [comment]
Uploaded the artifact to Bintray.com. Please check it. 
https://bintray.com/embulk-input-s3/maven/embulk-util-aws-credentials/0.2.8

**Comment by hito4t** [comment]
@muga 
Thank you!
@toyama0919 
embulk-util-aws-credentials has been uploaded!

**Comment by toyama0919** [comment]
embulk-util-aws-credentials applied.
@hito4t @frsyuki 

>if embulk-output-redshift append prefix "aws_" to property names.

this is not responded.
To use AwsCredentialsTask and maintaining compatibility.

see.
https://github.com/embulk/embulk-input-s3/blob/master/embulk-util-aws-credentials/src/main/java/org/embulk/util/aws/credentials/AwsCredentialsTask.java

**Comment by hito4t** [comment]
@toyama0919 Thank you!

>>  if embulk-output-redshift append prefix "aws_" to property names.

> this is not responded.
> To use AwsCredentialsTask and maintaining compatibility.

We can maintain backward compatibility even with `AwsCredentialsTaskWithPrefix` by some additional code.

1. Add backward compatibility properties to `RedshiftPluginTask`.
<pre>
        // for backward compatibility
        @Config("access_key_id")
        @ConfigDefault("null")
        Optional<String> getOldAccessKeyId();

        // for backward compatibility
        @Config("secret_access_key")
        @ConfigDefault("null")
        Optional<String> getOldSecretAccessKey();
</pre>

2. Copy these properties to new prefixed properties.
<pre>
    @Override
    protected RedshiftOutputConnector getConnector(PluginTask task, boolean retryableMetadataOperation)
    {
        RedshiftPluginTask t = (RedshiftPluginTask) task;
        if ("basic".equals(t.getAuthMethod())) {
            if (t.getOldAccessKeyId().isPresent() && !t.getAccessKeyId().isPresent()) {
                logger.warn("'access_key_id' is deprecated. Please use 'aws_access_key_id'.");
                t.setAccessKeyId(t.getOldAccessKeyId());
            }
            if (t.getOldSecretAccessKey().isPresent() && !t.getSecretAccessKey().isPresent()) {
                logger.warn("'secret_access_key' is deprecated. Please use 'aws_secret_access_key'.");
                t.setSecretAccessKey(t.getOldSecretAccessKey());
            }
        }
        ...
</pre>

I think backward compatibility and appropriate property names are both very important.

**Comment by toyama0919** [comment]
@hito4t 
Ah, I see.
I'll fix it.

**Comment by toyama0919** [comment]
@hito4t 
applied review.

**Comment by hito4t** [comment]
@toyama0919  Thank you!

I've updated README to clarify that access_key_id and secret_access_key are deprecated, and merged.

**Pull request merged**
