### PR TITLE
Run GitHub Actions on the Pull request.

### PR DESCRIPTION
**Pull request by hiroyuki-sato**
Fixed missing update in #314

### CODE REVIEW

**Comment by hiroyuki-sato** [comment]
@dmikurube, Could you take a look when you get a chance?

**Review by dmikurube — APPROVED** [review]
LGTM!

**Comment by hiroyuki-sato** [comment]
@dmikurube Thanks! I don't have permission. Could you merge this?

**Comment by dmikurube** [comment]
Merged. Thanks!

**Pull request merged**
