### PR TITLE
Enable Travis CI

### PR DESCRIPTION
**Pull request by dmikurube**
@hito4t @muga Although no tests may be executed yet, just adding configurations, and compiling there. Can you have a look?

### CODE REVIEW

**Comment by hito4t** [comment]
@dmikurube 
Great!

**Comment by hito4t** [comment]
@dmikurube 
The Travis CI failed.
https://travis-ci.org/embulk/embulk-output-jdbc/builds/303411000?utm_source=github_status&utm_medium=notification
Do you understand that cause?

**Comment by dmikurube** [comment]
@hito4t Ah, the PR may need to be rebased onto this #212 to enable Travis correctly. (#209 does not have correct `.travis.yml`.)

Okay, I'm merging this PR soon.

**Comment by dmikurube** [comment]
Merged. (Cc: @muga)

**Comment by muga** [comment]
👍

**Pull request merged**
